# http://travis-ci.org/#!/mitxlti/pylti
language: python
sudo: false
python:
    - 2.7
install:
    - python setup.py install --quiet
    - pip install --upgrade -r test_requirements.txt
    - pip install coveralls
script:
    - python setup.py test --coverage --pep8 --flakes
    - coverage run --source=pylti setup.py test 
after_success: 
    coveralls

